version: "3"

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - back-tier

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "10092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1" #topic name : number of partitions : number of replicas.
    networks:
      - back-tier

networks:
  back-tier: