version: "3"

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - back-tier

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "19092:19092"
    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      https://github.com/apache/kafka/blob/trunk/config/log4j.properties
#      LOG4J_LOGGER_ORG_APACHE_KAFKA: DEBUG
#      LOG4J_LOGGER_KAFKA: DEBUG
#      LOG4J_LOGGER_KAFKA_REQUEST_LOGGER: DEBUG
#      LOG4J_ROOTLOGGER: DEBUG
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS:
        #topic name : number of partitions : number of replicas.
        "executions:1:1,deposits:1:1"
    networks:
      - back-tier

networks:
  back-tier: