version: "3"

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - back-tier

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "10092:9092"
    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:10092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:10092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS:
        #topic name : number of partitions : number of replicas.
        "executions:1:1,deposits:1:1"
    networks:
      - back-tier

networks:
  back-tier: