#  CREATE USER 'zipkin'@'localhost' IDENTIFIED BY 'password';
#  GRANT ALL PRIVILEGES ON *.* TO 'zipkin'@'localhost';
#  CREATE DATABASE zipkin;
#  USE zipkin;
#  SCHEMA: https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/mysql-v1/src/main/resources/mysql.sql
# zipkin config /zipkin-server-2.12.5.jar!/zipkin-server-shared.yml

spring:
  application:
    name: zipkin
  main:
    web-application-type: none
  datasource:
    url: jdbc:mysql://localhost:55555/zipkin?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: zipkin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: true

zipkin:
  storage:
    type: mysql

armeria:
  ports:
    - port: 9411
      protocols: http

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level.org.springframework: DEBUG