server:
  port: 8081
  error.whitelabel.enabled: false

spring:
  thymeleaf.cache: false
  thymeleaf.enabled: true
  thymeleaf.prefix: classpath:/templates/
  thymeleaf.suffix: .html
  mvc.throw-exception-if-no-handler-found: true
  mvc.static-path-pattern: /static/**
