spring:
  application:
    name: discovery

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8761

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 4000
    responseCacheUpdateIntervalMs: 3000
