spring:
  application:
    name: discovery
  zipkin:
    baseUrl: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8761

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 4000
    responseCacheUpdateIntervalMs: 3000

#logging.level.org.springframework: DEBUG