####### OVERRIDE OPTION ########
# override via WM option: -Dparam.mysql.host=localhost

param.mysql.host: mysqldb
param.discovery.host: discovery

#######


spring:
  application:
    name: justitia
  mvc.throw-exception-if-no-handler-found: true
  mvc.static-path-pattern: /static/**
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/

  datasource:
    url: jdbc:mysql://${param.mysql.host}:55551/justitia?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: justitia
    password: password
    driver-class-name: com.mysql.jdbc.Driver

    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000

  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  jpa:
#    open-in-view: false
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml

jwt:
  certificate:
    store:
      key-store: classpath:keystore.p12
      key-store-password: srch4app
    key:
      keyAlias: tomcat
      keyPassword: srch4app

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8002
  ssl: #keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
    key-store: classpath:keystore.p12
    key-store-password: srch4app
    keyStoreType: PKCS12
    keyAlias: tomcat
    enabled: true
  servlet.session.cookie.name: OAUTHSESSIONID

  thymeleaf.cache: false
  thymeleaf.enabled: true
  thymeleaf.prefix: classpath:/templates/
  thymeleaf.suffix: .html

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://${param.discovery.host}:8761/eureka/

#logging.level.org.springframework: DEBUG

