spring:
  application:
    name: zuul
  mvc.throw-exception-if-no-handler-found: true
  mvc.static-path-pattern: /static/**

  zipkin:
    baseUrl: http://localhost:9411/

  redis.host: 127.0.0.1
  redis.port: 6379

#  datasource:
#    url: jdbc:mysql://localhost:55555/justitia
#    username: justitia
#    password: password
#    driver-class-name: com.mysql.jdbc.Driver
#
#    hikari:
#      minimumIdle: 5
#      maximumPoolSize: 20
#      idleTimeout: 30000
#      maxLifetime: 2000000
#      connectionTimeout: 30000
#
#  jpa:
#    open-in-view: false
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: none

#feign:
#  oauth2:
#    client-id: trusted-client
#    client-secret: trusted-client
#    supported-apis: omnidrive-api,exodus-api

management:
  endpoints:
    web:
      exposure:
          include: "*"

server:
  port: 8090
  ssl: #keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
    key-store: classpath:keystore.p12
    key-store-password: srch4app
    keyStoreType: PKCS12
    keyAlias: tomcat
    #    keytool -import -file gskv.crt -alias gskv -keystore truststore.jks
    #    below configuration is not working properly so it is configured in com.apps.cloud.zuul.security.SSLConfig
    trust-store: classpath:truststore.jks
    trust-store-password: srch4app
    trust-store-type: JKS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ribbon:
    eager-load:
      enabled: true
  retryable: true
  ignoredServices: '*'
  prefix: /
  routes:
#    oauth:
#      path: /oauth/**
#      sensitiveHeaders:
#      serviceId: justitia
#      stripPrefix: false
#    justitia-api:
#      path: /justitia-api/**
#      sensitiveHeaders:
#      serviceId: justitia
#      stripPrefix: false
    sdapplication:
      path: /**
      sensitiveHeaders:
      serviceId: SDApplication
      stripPrefix: false

ribbon:
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ReadTimeout: 60000

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

feign:
  oauth2:
    client-id: sdapplication
    client-secret: sdapplication_secret

logging.level.org.springframework: DEBUG