spring:
  application:
    name: potok
  redis.host: 127.0.0.1
  redis.port: 6379

management:
  endpoints:
    web:
      exposure:
          include: "*"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

socket-io-server:
  host: localhost
  port: 9092

certificate:
  store:
    key-store: classpath:keystore.p12
    key-store-password: srch4app

logging.level.org.springframework: DEBUG