####### OVERRIDE OPTION ########
# override via WM option: -Dmysql.host=localhost

param.redis.host: redis
param.discovery.host: discovery

#######

spring:
  application:
    name: potok
  redis.host: ${param.redis.host}
  redis.port: 6379

management:
  endpoints:
    web:
      exposure:
          include: "*"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://${param.discovery.host}:8761/eureka/

socket-io-server:
  port: 9092

certificate:
  store:
    key-store: classpath:keystore.p12
    key-store-password: srch4app

session.test-mode-authentication: true

exchange:
  order-size: 100 #Chunk size that is being pulled from MkDataServer and initialization.
  symbol-size: 100
  price:
    min-range: 10
    max-range: 90
  accounts-size: 200
  cancel-balance-return-delay: 10
  speed: MAX #programm argument: --exchange.speed=NORMAL
  #speed available options:
    #MAX production mode no thread sleep almost 100% CPU consupmtion. Mostly used for no functional testing to reveal concurrent issues.
    #FAST 1 ms OrderCreator 300 ms MkDataServer thread sleep
    #NORMAL 10 ms OrderCreator 3000 ms MkDataServer thread sleep
    #SLOW 100 ms OrderCreator 30000 ms MkDataServer thread sleep
    #DEAD 1000 ms OrderCreator 300000 ms MkDataServer thread sleep
    #STOP OrderCreator/MkDataServer not started
  shutdowner.timeout: 0 #milliseconds 0 disabled.
logging.level.org.springframework: DEBUG