server:
  port: 8081
  error.whitelabel.enabled: false

spring:
  application:
    name: SDApplication
  thymeleaf.cache: false
  thymeleaf.enabled: true
  thymeleaf.prefix: classpath:/templates/
  thymeleaf.suffix: .html

  mvc.throw-exception-if-no-handler-found: true
  mvc.static-path-pattern: /static/**
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/

#---
#spring:changelog-master.yaml
#  profiles: h2
  datasource:
    url: jdbc:mysql://localhost:55555/sdapplication?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: sdapplication
    password: password
    driver-class-name: com.mysql.jdbc.Driver

    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  #Session persistence
  redis.host: 127.0.0.1
  redis.port: 6379

#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.Oracle12cDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level.org.springframework: DEBUG
logging.level.org.hibernate: ERROR

data-creation:
  address-store: classpath:db/addresses-us-all.json #use file: to specify absolute/relative location on the file system.

cartographer:
  origin-map-cartographer-url: http://localhost:8510/originmap
  value-map-cartographer-url: http://localhost:8510/valuemap
  pollution-map-cartographer-url: http://localhost:8510/pollutionmap