server:
  port: 8081
  error.whitelabel.enabled: false

spring:
  application:
    name: SDApplication
  thymeleaf.cache: false
  thymeleaf.enabled: true
  thymeleaf.prefix: classpath:/templates/
  thymeleaf.suffix: .html

  mvc.throw-exception-if-no-handler-found: true
  mvc.static-path-pattern: /static/**
  session.cookie.secure: true
  session.cookie.http-only: true

  zipkin:
    baseUrl: http://localhost:9411/

#---
#spring:changelog-master.yaml
#  profiles: h2
  datasource:
    url: jdbc:h2:file:./data/db/spDb;MODE=Oracle
    username: sa
    password:
    type:
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog-master.yaml

#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.Oracle12cDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level.org.springframework: DEBUG
logging.level.org.hibernate: ERROR

security:
  oauth2:
    jwt:
      signing-key: my-secret-key

data-creation:
  address-store: classpath:db/addresses-us-all.json #use file: to specify absolute/relative location on the file system.