server:
  port: 8081
  error.whitelabel.enabled: false

spring:
  thymeleaf.cache: false
  thymeleaf.enabled: true
  thymeleaf.prefix: classpath:/templates/
  thymeleaf.suffix: .html

  mvc.throw-exception-if-no-handler-found: true
  mvc.static-path-pattern: /static/**

#---
#spring:changelog-master.yaml
#  profiles: h2
  datasource:
    url: jdbc:h2:mem:spDb;MODE=Oracle
    username: sa
    password:
    type:
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog-master.yaml