version: "3"

services:

  auth_demo:
    image: auth_demo
    container_name: auth_demo
    ports:
      - "8097:8097"
      - "9093:9093"
    networks:
      - back-tier
      - front-tier

  discovery:
    image: discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - back-tier

  justitia:
    image: justitia
    container_name: justitia
    ports:
      - "8002:8002"
    networks:
      - front-tier
      - back-tier

  zuul:
    image: zuul
    container_name: zuul
    ports:
      - "8090:8090"
    networks:
      - front-tier
      - back-tier

  sdapplication:
    image: sdapplication
    container_name: sdapplication
    ports:
      - "8081:8081"
    networks:
      - back-tier

  potok:
    stop_grace_period: 30s #does not apply when stopped from idea use docker stop -t 30 potok
    image: potok
    container_name: potok
    ports:
      - "9092:9092"
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - back-tier

  db:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    expose:
      - 55555
    environment:
      MYSQL_TCP_PORT: 55555
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "55555:55555"
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - back-tier

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /Users/georgy.saukov/Desktop/dev/soft/nginx/html:/etc/nginx/html
      - /Users/georgy.saukov/Desktop/dev/soft/nginx/conf/nginx.conf:/etc/nginx/nginx.conf #sometimes it may produce folder nginx.conf on host then rm the container.
    ports:
      - "9020:9020"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=9020
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - front-tier

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - back-tier

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "15672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - back-tier

volumes:
  db-data:
  cassandra-data:
  rabbitmq_data:

networks:
  front-tier:
  back-tier: